version: "2"

services:
  redis:
    command: redis-server /etc/redis.conf
    image: redis:5.0.5-alpine
    volumes:
      - ./room-service/redis.conf:/etc/redis.conf

  roomapi:
    build:
      context: ./room-service
      dockerfile: Dockerfile
    command: nodemon ./bin/www
    environment:
      - VIRTUAL_HOST=rooms.my.docker
    volumes:
      - ./room-service:/app/src
    ports:
      - 3000:3001
    environment: 
      - JANUS_ADMIN_SECRET
      - JANUS_TOKEN_SECRET
      - JANUS_URL
    depends_on:
      - redis
